spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/pocket_order?characterEncoding=utf-8&serverTimezone=Asia/Shanghai"
    username: pocket_order
    password: password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 30000
  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: pco_
      cache-null-values: false
      time-to-live: 400s
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB # 文件大小限制
      max-request-size: 20MB
file:
  upload-dir: ./uploads/
aliyun:
  oss:
    endpoint: oss-cn-guangzhou.aliyuncs.com               # OSS区域
    accessKeyId: xxxxxxxxx                                # AccessKeyId
    accessKeySecret: xxxxxxxxx                            # AccessKeySecret
    bucketName: xxxxxxxxx                                 # 存储桶名称
    dir: uploads/                                         # 上传目录，设置为空字符串表示根目录

server:
  port: 7000

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl